
import Project.ConnectionProvider;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Billing extends javax.swing.JFrame {
    
    
   public int finalTotal=0;
    public Billing() {
        initComponents();
       
        SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy");
         Date date=new Date(); 
         Date.setText(df.format(date));
         
         DateTimeFormatter dfr=DateTimeFormatter.ofPattern("HH:MM:SS");
         LocalDateTime t= LocalDateTime.now();
         Time.setText(dfr.format(t));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bContactNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bEmail = new javax.swing.JTextField();
        bAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pRate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pQuantity = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pDescription = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        PaidAmount = new javax.swing.JTextField();
        ReturnAmount = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        DueAmount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showtxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 180));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing frame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing ani.gif"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 100));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 100));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setText("Time :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, -1, -1));

        Date.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        Time.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Time.setText("Time");
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 93, 1130, 9));

        jLabel5.setBackground(new java.awt.Color(0, 204, 153));
        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel5.setText("Buyers Details: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 204, 153));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 153, -1, -1));

        bName.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        bName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNameActionPerformed(evt);
            }
        });
        getContentPane().add(bName, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 150, 198, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setText("Contact No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 153, -1, -1));

        bContactNo.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        bContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContactNoActionPerformed(evt);
            }
        });
        getContentPane().add(bContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 186, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 153, -1, -1));

        bEmail.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        bEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmailActionPerformed(evt);
            }
        });
        getContentPane().add(bEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 150, 211, -1));

        bAddress.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        bAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddressActionPerformed(evt);
            }
        });
        getContentPane().add(bAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 150, 207, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 153, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 204, 153));
        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel10.setText("Product Details: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 204, 153));
        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel11.setText("Product Id ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 244, -1, -1));

        pid.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 241, 72, -1));

        pName.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 241, 139, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel12.setText("Product Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 244, -1, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel13.setText("Product Rate");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 244, -1, -1));

        pRate.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().add(pRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 241, 99, -1));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel14.setText("Quantity");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 244, -1, -1));

        pQuantity.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().add(pQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 241, 116, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 191, 1130, 10));

        pDescription.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().add(pDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 241, 186, -1));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel15.setText("Desciption");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 244, -1, -1));

        Add.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1039, 282, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 329, 1130, 10));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        Table.setSelectionBackground(new java.awt.Color(255, 0, 102));
        Table.getTableHeader().setResizingAllowed(false);
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 580, 200));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel16.setText("Calculation Details");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 340, -1, -1));

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel17.setText("TOTAL");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel18.setText("PAID AMOUNT");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel19.setText("RETURN AMOUNT");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        Total.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 373, 167, -1));

        PaidAmount.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        PaidAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidAmountActionPerformed(evt);
            }
        });
        getContentPane().add(PaidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 167, -1));

        ReturnAmount.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().add(ReturnAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 169, -1));

        Save.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 370, 89, -1));

        Print.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        Print.setText("PRINT");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        getContentPane().add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 89, -1));

        Cancel.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        Cancel.setText("CANCEL");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, -1, -1));

        DueAmount.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        DueAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueAmountActionPerformed(evt);
            }
        });
        getContentPane().add(DueAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 167, -1));

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel20.setText("DUE AMOUNT");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        Reset.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 89, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbg.png"))); // NOI18N
        jLabel21.setToolTipText("");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        showtxt.setColumns(20);
        showtxt.setRows(5);
        jScrollPane2.setViewportView(showtxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNameActionPerformed
        // TODO add your handling code here:
        String name=bName.getText();
        
        Connection con;
        try {
            con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select* from addbuyers where name like '"+name+"%'");
            if(rs.next()){
            bName.setText(rs.getString(1));
            bContactNo.setText(rs.getString(2));
            bEmail.setText(rs.getString(3));
            bAddress.setText(rs.getString(4));
            
            
            }
            else{
            
            bContactNo.setText("");
            bEmail.setText("");
            bAddress.setText("");
            
            }
            
            
        } catch (ClassNotFoundException ex) {
          JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_bNameActionPerformed

    private void bContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContactNoActionPerformed
        // TODO add your handling code here:
         String contact=bContactNo.getText();
        
        Connection con;
        try {
            con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select* from addbuyers where ContactNo like '"+contact+"%'");
            if(rs.next()){
            bName.setText(rs.getString(1));
            bContactNo.setText(rs.getString(2));
            bEmail.setText(rs.getString(3));
            bAddress.setText(rs.getString(4));
            
            
            }
            else{
            
            bName.setText("");
            bEmail.setText("");
            bAddress.setText("");
            
            }
            
            
        } catch (ClassNotFoundException ex) {
          JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bContactNoActionPerformed

    private void bEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmailActionPerformed
        String email=bEmail.getText();
        
        Connection con;
        try {
            con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select* from addbuyers where Email like '"+email+"%'");
            if(rs.next()){
            bName.setText(rs.getString(1));
            bContactNo.setText(rs.getString(2));
            bEmail.setText(rs.getString(3));
            bAddress.setText(rs.getString(4));
            
            
            }
            else{
            
            bContactNo.setText("");
            bName.setText("");
            bAddress.setText("");
            
            }
            
            
        } catch (ClassNotFoundException ex) {
          JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bEmailActionPerformed

    private void bAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddressActionPerformed
 String address=bAddress.getText();
        
        Connection con;
        try {
            con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select* from product where Address like '"+address+"%'");
            if(rs.next()){
            bName.setText(rs.getString(1));
            bContactNo.setText(rs.getString(2));
            bEmail.setText(rs.getString(3));
            bAddress.setText(rs.getString(4));
            
            
            }
            else{
            
            bContactNo.setText("");
            bEmail.setText("");
            bEmail.setText("");
            
            }
            
            
        } catch (ClassNotFoundException ex) {
          JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bAddressActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
         String id=pid.getText();
        
        Connection con;
        try {
            con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select* from product where ProductId= '"+id+"'");
            if(rs.next()){
                
            pName.setText(rs.getString(2));
            pRate.setText(rs.getString(3));
            pQuantity.setText("1");
            pDescription.setText(rs.getString(4));
            
            
            }
            else{
            
            pName.setText("");
            pRate.setText("");
            pQuantity.setText("");
            pDescription.setText("");
            
            }
            
            
        } catch (ClassNotFoundException ex) {
          JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_pidActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        
        if(pName.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Enter item First!");
        }
        else{
        int price=Integer.parseInt(pRate.getText());
        int quantity=Integer.parseInt(pQuantity.getText());
        int total=price*quantity;
        DefaultTableModel df=(DefaultTableModel)Table.getModel();
        df.addRow(new Object[]{pName.getText(),pDescription.getText(),price,quantity,total});
        finalTotal=finalTotal+total;
        String FinalTotal=String.valueOf(finalTotal);
        Total.setText(FinalTotal);
        
        }
    }//GEN-LAST:event_AddActionPerformed

    private void PaidAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidAmountActionPerformed
        // TODO add your handling code here:
        int paid=Integer.parseInt(PaidAmount.getText());
        if(finalTotal>paid){
        ReturnAmount.setText("0");
        DueAmount.setText(String.valueOf(finalTotal-paid));
        }
        else{
         DueAmount.setText("0");
         ReturnAmount.setText(String.valueOf(paid-finalTotal));
        }
        DueAmount.setEditable(false);
        ReturnAmount.setEditable(false);
       
    }//GEN-LAST:event_PaidAmountActionPerformed

    private void DueAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueAmountActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DueAmountActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
       
        try {
            /*
           int x=Table.getRowCount();
           int y=Table.getColumnCount();
           showtxt.append("Name                 Description                 Rate                 Quantity                 Total\n");
          
           for(int i=0;i<x;i++){
               for(int j=0;j<y;j++){
                   if(j==4){
                   
                   System.out.println("\n");
                   }else{
                    showtxt.append(Table.getValueAt(i,j).toString()+"             ");
                   } 
               }
              
           }
           */
          Table.print();
          
           
       } catch (PrinterException ex) {
           Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_PrintActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String name=bName.getText();
        String contact=bContactNo.getText();
        String email=bEmail.getText();
        String address=bAddress.getText();
        String path="F:\\SavedInfo\\"+name+".txt";
        File file=new File(path);
        
        
       try {
           FileWriter f=new FileWriter(file);
          
           
           f.write("		   	Billing Management System\n");
           f.write("			Contact No: 01921456068\n");
           f.write("\n\n");
           f.write("Date and Time :  "+Date.getText()+"  "+Time.getText()+"\n");
           f.write("Buyers Details: \n");
           f.write("\nName       : "+name);
           f.write("\nContact No  : "+contact);
           f.write("\nEmail       : "+email);
           f.write("\nAddress     : "+address);
           f.write("\n\n");
          
           f.write("\n\n\n");
           f.write("\nTotal Amount : "+Total.getText());
           f.write("\nPaid Amount  : "+PaidAmount.getText());
           f.write("\nDue Amount   : "+DueAmount.getText());
           f.write("\nReturn Amount: "+ReturnAmount.getText());
           f.write("\n\n\n");
           f.write("\nThanks for visiting! Please Come Again");
           f.write("\nRBT");
           
           
         
          f.close();
          JOptionPane.showMessageDialog(null, "Bill Genereted!");
       } catch (IOException ex) {
           Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
        
       
        
    }//GEN-LAST:event_SaveActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Billing().setVisible(true);
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
         
            public void run() {
               
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField DueAmount;
    private javax.swing.JTextField PaidAmount;
    private javax.swing.JButton Print;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField ReturnAmount;
    private javax.swing.JButton Save;
    private javax.swing.JTable Table;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField bAddress;
    private javax.swing.JTextField bContactNo;
    private javax.swing.JTextField bEmail;
    private javax.swing.JTextField bName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField pDescription;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pQuantity;
    private javax.swing.JTextField pRate;
    private javax.swing.JTextField pid;
    private javax.swing.JTextArea showtxt;
    // End of variables declaration//GEN-END:variables
}
