
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Home extends javax.swing.JFrame {
    int z=0;

    public Home() {
        initComponents();
        addBuyers.setVisible(false);
        UpdateBuyers.setVisible(false);
        DeleteBuyers.setVisible(false);
        AddProducts.setVisible(false);
        UpdateProducts.setVisible(false);
        ProductsDetails.setVisible(false);
        Deleteproduct.setVisible(false);
         buyersDetails.setVisible(false);
         BuyersDetails.setVisible(false);
        Billing.setVisible(false);
        Logout.setVisible(false);
        CloseApp.setVisible(false);
        DPI.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cshow = new javax.swing.JButton();
        addBuyers = new javax.swing.JButton();
        UpdateBuyers = new javax.swing.JButton();
        DeleteBuyers = new javax.swing.JButton();
        AddProducts = new javax.swing.JButton();
        UpdateProducts = new javax.swing.JButton();
        Deleteproduct = new javax.swing.JButton();
        ProductsDetails = new javax.swing.JButton();
        Billing = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        CloseApp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buyersDetails = new javax.swing.JButton();
        BuyersDetails = new javax.swing.JLabel();
        DPI = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control hide and show.png"))); // NOI18N
        Cshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CshowMouseClicked(evt);
            }
        });
        getContentPane().add(Cshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        addBuyers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyer.png"))); // NOI18N
        addBuyers.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addBuyersComponentShown(evt);
            }
        });
        addBuyers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBuyersActionPerformed(evt);
            }
        });
        getContentPane().add(addBuyers, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        UpdateBuyers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update buyer.png"))); // NOI18N
        UpdateBuyers.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateBuyersComponentShown(evt);
            }
        });
        UpdateBuyers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyersActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBuyers, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        DeleteBuyers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete buyer.png"))); // NOI18N
        DeleteBuyers.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteBuyersComponentShown(evt);
            }
        });
        DeleteBuyers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBuyersActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBuyers, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        AddProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new product.png"))); // NOI18N
        AddProducts.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AddProductsComponentShown(evt);
            }
        });
        AddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductsActionPerformed(evt);
            }
        });
        getContentPane().add(AddProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        UpdateProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update product.png"))); // NOI18N
        UpdateProducts.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateProductsComponentShown(evt);
            }
        });
        UpdateProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductsActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        Deleteproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete product.png"))); // NOI18N
        Deleteproduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteproductComponentShown(evt);
            }
        });
        Deleteproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteproductActionPerformed(evt);
            }
        });
        getContentPane().add(Deleteproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        ProductsDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details product.png"))); // NOI18N
        ProductsDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProductsDetailsComponentShown(evt);
            }
        });
        ProductsDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(ProductsDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        Billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        Billing.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BillingComponentShown(evt);
            }
        });
        Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingActionPerformed(evt);
            }
        });
        getContentPane().add(Billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        Logout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LogoutComponentShown(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, -1));

        CloseApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        CloseApp.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CloseAppComponentShown(evt);
            }
        });
        CloseApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseAppActionPerformed(evt);
            }
        });
        getContentPane().add(CloseApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setText("New Buyers");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setText("Update Info");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setText("Delete Buyers");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setText("New Products");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel5.setText("Update Products");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setText("Product Details");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setText("Delete Products");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setText("Billing");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel9.setText("Log out");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel10.setText("Close ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 120, -1, -1));

        buyersDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer Details.png"))); // NOI18N
        buyersDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                buyersDetailsComponentShown(evt);
            }
        });
        buyersDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyersDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(buyersDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        BuyersDetails.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        BuyersDetails.setText("Buyers Details");
        BuyersDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BuyersDetailsComponentShown(evt);
            }
        });
        getContentPane().add(BuyersDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        DPI.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        DPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        DPI.setText("DPI");
        DPI.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DPIComponentShown(evt);
            }
        });
        DPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPIActionPerformed(evt);
            }
        });
        getContentPane().add(DPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.PNG"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseAppActionPerformed
       int a=JOptionPane.showConfirmDialog(null, "Do you really want to close?","Select",JOptionPane.YES_NO_OPTION);
       if(a==0){
       System.exit(0);
       }
    }//GEN-LAST:event_CloseAppActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
      int a=JOptionPane.showConfirmDialog(null, "Do you really want to Log Out?","Select",JOptionPane.YES_NO_OPTION);
      if(a==0){
       setVisible(false);
      new LoginForm().setVisible(true);
      }
     
    }//GEN-LAST:event_LogoutActionPerformed

    private void CshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CshowMouseClicked
        // TODO add your handling code here:
        if(z==0){
            try {
                Thread.sleep(250);
                addBuyers.setVisible(true);
                jLabel1.setVisible(true);
                DPI.setVisible(true);
            } catch (InterruptedException e) {
               
            }
        }
        else{
        
        addBuyers.setVisible(false);
        UpdateBuyers.setVisible(false);
        DeleteBuyers.setVisible(false);
        AddProducts.setVisible(false);
        UpdateProducts.setVisible(false);
        ProductsDetails.setVisible(false);
        Deleteproduct.setVisible(false);
        buyersDetails.setVisible(false);
        Billing.setVisible(false);
        Logout.setVisible(false);
        CloseApp.setVisible(false);
        jLabel1.setVisible(false);
        BuyersDetails.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        DPI.setVisible(false);
        z=0;
        
        
        }
    }//GEN-LAST:event_CshowMouseClicked

    private void addBuyersComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addBuyersComponentShown
        // TODO add your handling code here:
        try {
                Thread.sleep(250);
                UpdateBuyers.setVisible(true);
                jLabel2.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
       
    }//GEN-LAST:event_addBuyersComponentShown

    private void UpdateBuyersComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateBuyersComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(250);
                buyersDetails.setVisible(true);
                BuyersDetails.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_UpdateBuyersComponentShown

    private void DeleteBuyersComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteBuyersComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(250);
                AddProducts.setVisible(true);
                jLabel4.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_DeleteBuyersComponentShown

    private void AddProductsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AddProductsComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(250);
                UpdateProducts.setVisible(true);
                jLabel5.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_AddProductsComponentShown

    private void UpdateProductsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateProductsComponentShown
        // TODO add your handling code here:
          try {
                Thread.sleep(250);
                ProductsDetails.setVisible(true);
                jLabel6.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_UpdateProductsComponentShown

    private void ProductsDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProductsDetailsComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(250);
                Deleteproduct.setVisible(true);
                jLabel7.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_ProductsDetailsComponentShown

    private void DeleteproductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteproductComponentShown
        // TODO add your handling code here:
          try {
                Thread.sleep(250);
                Billing.setVisible(true);
                jLabel8.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_DeleteproductComponentShown

    private void BillingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BillingComponentShown
        // TODO add your handling code here:
        try {
                Thread.sleep(250);
                Logout.setVisible(true);
                jLabel9.setVisible(true);
                
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_BillingComponentShown

    private void LogoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LogoutComponentShown
        // TODO add your handling code here:
        try {
                Thread.sleep(250);
                CloseApp.setVisible(true);
                jLabel10.setVisible(true);
                z=1;
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_LogoutComponentShown

    private void CloseAppComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CloseAppComponentShown
       
    }//GEN-LAST:event_CloseAppComponentShown

    private void addBuyersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBuyersActionPerformed
        // TODO add your handling code here:
        new addBuyers().setVisible(true);
    }//GEN-LAST:event_addBuyersActionPerformed

    private void UpdateBuyersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyersActionPerformed
        // TODO add your handling code here:
        new updateBuyers().setVisible(true);
    }//GEN-LAST:event_UpdateBuyersActionPerformed

    private void buyersDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_buyersDetailsComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(250);
                DeleteBuyers.setVisible(true);
                jLabel3.setVisible(true);
                
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_buyersDetailsComponentShown

    private void BuyersDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BuyersDetailsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyersDetailsComponentShown

    private void buyersDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyersDetailsActionPerformed
        // TODO add your handling code here:
      new BuyersDetails().setVisible(true);
    }//GEN-LAST:event_buyersDetailsActionPerformed

    private void DeleteBuyersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBuyersActionPerformed
        // TODO add your handling code here:
        new DeleteBuyers().setVisible(true);
    }//GEN-LAST:event_DeleteBuyersActionPerformed

    private void AddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductsActionPerformed
        // TODO add your handling code here:
        new newProduct().setVisible(true);
    }//GEN-LAST:event_AddProductsActionPerformed

    private void UpdateProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductsActionPerformed
        // TODO add your handling code here:
        new updateProduct().setVisible(true);
    }//GEN-LAST:event_UpdateProductsActionPerformed

    private void ProductsDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsDetailsActionPerformed
        // TODO add your handling code here:
        new productDetails().setVisible(true);
    }//GEN-LAST:event_ProductsDetailsActionPerformed

    private void DeleteproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteproductActionPerformed
        // TODO add your handling code here:
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_DeleteproductActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
        new Billing().setVisible(true);
    }//GEN-LAST:event_BillingActionPerformed

    private void DPIComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DPIComponentShown
        // TODO add your handling code here:
        try {
                Thread.sleep(250);
                UpdateBuyers.setVisible(true);
                jLabel2.setVisible(true);
               
            } catch (InterruptedException e) {
                
            }
    }//GEN-LAST:event_DPIComponentShown

    private void DPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPIActionPerformed
        // TODO add your handling code here:
        new ShowDeleted().setVisible(true);
    }//GEN-LAST:event_DPIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProducts;
    private javax.swing.JButton Billing;
    private javax.swing.JLabel BuyersDetails;
    private javax.swing.JButton CloseApp;
    private javax.swing.JButton Cshow;
    private javax.swing.JButton DPI;
    private javax.swing.JButton DeleteBuyers;
    private javax.swing.JButton Deleteproduct;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ProductsDetails;
    private javax.swing.JButton UpdateBuyers;
    private javax.swing.JButton UpdateProducts;
    private javax.swing.JButton addBuyers;
    private javax.swing.JButton buyersDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
